#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'rpc_service_types'

module Rpc
  module RpcService
    class Client
      include ::Thrift::Client

      def GetName(name)
        send_GetName(name)
        return recv_GetName()
      end

      def send_GetName(name)
        send_message('GetName', GetName_args, :name => name)
      end

      def recv_GetName()
        result = receive_message(GetName_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'GetName failed: unknown result')
      end

    end

    class Processor
      include ::Thrift::Processor

      def process_GetName(seqid, iprot, oprot)
        args = read_args(iprot, GetName_args)
        result = GetName_result.new()
        result.success = @handler.GetName(args.name)
        write_result(result, oprot, 'GetName', seqid)
      end

    end

    # HELPER FUNCTIONS AND STRUCTURES

    class GetName_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      NAME = 1

      FIELDS = {
        NAME => {:type => ::Thrift::Types::STRING, :name => 'name'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class GetName_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::STRING, :name => 'success'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

  end

end
